name: Nightfall Package Deploy to PyPI

on:
  release:
    types: [published]

jobs:
  test-and-publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
          pip install -e .
      - name: Test with unittest
        env:
          NIGHTFALL_CONDITION_SET: ${{ secrets.NIGHTFALL_CONDITION_SET }}
          NIGHTFALL_TOKEN: ${{ secrets.NIGHTFALL_TOKEN }}
        run: |
          python -m unittest discover
      - name: Build a binary wheel and source tarball
        run: |
          python -m build --sdist --wheel --outdir dist/
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
